### ISSUE TITLE
Test fails because the structure of the output is different from the general structure

### ISSUE THREAD

**Issue by DhanshreeA** [ersilia-os/eos8a4x#11]
The output JSON structure that we generally follow across all models is:
```JSON
{
    "input": {
        "key": "string",
        "input": "string",
        "text": "string"
    },
    "output": {
        "outcome": [...]
    }
}
```

However in this model the service.py file is modified to replace the key `outcome` with `descriptor`. Since the test looks for the values in `outcome` field, being unable to find this key, the test fails.

**Comment by GemmaTuron** [comment]
@DhanshreeA is this fixed now? the model works for me!

**Comment by DhanshreeA** [comment]
@GemmaTuron this is fixed. We don't depend on a specific key and rely solely on the output to inspect model's working.
